# Generated by Django 5.1.3 on 2024-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("BRA", "Brasil"),
                            ("EUA", "Estados Unidos"),
                            ("ENG", "Inglaterra"),
                            ("GER", "Alemanha"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
